#!/bin/bash

# WAREHOUSE PROJ 00/09

#--- ENV ---------------------------------------------

SCHOME="/zbox/proj_warehouse/warehouse"
DSTHOST="wh1.whiskey9.net"
DSTHOST="62.77.157.57"
DSTUSER="root"
DSTSSH="${DSTUSER}@${DSTHOST}"
PROJ=$1

#-----------------------------------------------------

echo "*****************************"
echo "    WAREHOUSE PROJ 00/09"
echo "*****************************"
echo

echo ":::: RUN builder ..."
echo ":::: scp builder ${DSTSSH}:/data/_builds/builder"
scp ${SCHOME}/builder ${DSTSSH}:/data/_builds/builder
ssh ${DSTSSH} "chmod a+x /data/_builds/builder"
ssh ${DSTSSH} "/data/_builds/builder $PROJ"


